# This is the config file for github
title: Amanda Huntington
email: amanda.n.huntington@gmail.com
description: Amanda Huntington's Personal Website
baseurl: "" 
url: "https://anhuntington.github.io/"
